version: '3.7'

services:
  consul-server:
    image: hashicorp/consul:1.10.0
    restart: always
    volumes:
     - ./server.json:/consul/config/server.json:ro
    network_mode: bridge
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"
  consul-client:
    image: hashicorp/consul:1.10.0
    restart: always
    volumes:
     - ./client.json:/consul/config/client.json:ro
    network_mode: bridge
    command: "agent"
